In [1]:
import numpy as np
from scipy.io import loadmat

data = loadmat('graph_topologies_only.mat')

In [2]:
data.keys()

dict_keys(['__header__', '__version__', '__globals__', 'graph_k4_add', 'graph_k4_torus', 'graph_k6_add', 'graph_k6_torus', 'graph_k8_add', 'graph_k8_torus'])

In [3]:
graph_k4_add = data['graph_k4_add']
graph_k4_torus = data['graph_k4_torus']

print(graph_k4_add.shape)

(64, 64, 2, 8, 4)


In [4]:
# loop 선택 (MATLAB 1 → Python 0)
loop = 0   # loop=1에 해당

num_del = graph_k4_add.shape[3]   # 8
num_pa  = graph_k4_add.shape[4]   # 4

degree_sum_matrix = np.zeros((num_del, num_pa))

for d in range(num_del):      # 0~7
    for p in range(num_pa):   # 0~3

        A = graph_k4_add[:, :, loop, d, p]   # 64×64 adjacency

        degree = np.sum(A, axis=1)           # 각 노드 degree
        deg_sum = np.sum(degree)             # degree 합계

        degree_sum_matrix[d, p] = deg_sum

# 출력
print("Degree sum for loop =", loop+1)
print(degree_sum_matrix)

Degree sum for loop = 1
[[424. 424. 424. 424.]
 [500. 500. 500. 500.]
 [576. 576. 576. 576.]
 [654. 654. 654. 654.]
 [730. 730. 730. 730.]
 [808. 808. 808. 808.]
 [884. 884. 884. 884.]
 [960. 960. 960. 960.]]


In [5]:
# loop 선택 (MATLAB 1 → Python 0)
loop = 0   # loop=1에 해당

num_del = graph_k4_torus.shape[3]   # 8
num_pa  = graph_k4_torus.shape[4]   # 4

degree_sum_matrix = np.zeros((num_del, num_pa))

for d in range(num_del):      # 0~7
    for p in range(num_pa):   # 0~3

        A = graph_k4_torus[:, :, loop, d, p]   # 64×64 adjacency

        degree = np.sum(A, axis=1)           # 각 노드 degree
        deg_sum = np.sum(degree)             # degree 합계

        degree_sum_matrix[d, p] = deg_sum

# 출력
print("Degree sum for loop =", loop+1)
print(degree_sum_matrix)

Degree sum for loop = 1
[[384. 384. 384. 384.]
 [384. 384. 384. 384.]
 [384. 384. 384. 384.]
 [384. 384. 384. 384.]
 [384. 384. 384. 384.]
 [384. 384. 384. 384.]
 [384. 384. 384. 384.]
 [384. 384. 384. 384.]]
